### ISSUE TITLE
TypeError: BroadcastChannel is not a constructor

### ISSUE THREAD

**Issue by notooth1** [tardis-dev/serum-vial#40]
I failed run serum-vial. Can anyone help?

```
$ npx serum-vial 
/mnt/Archive/Downloads/node_modules/serum-vial/dist/helpers.js:85
exports.minionReadyChannel = new BroadcastChannel('MinionReady');
                             ^

TypeError: BroadcastChannel is not a constructor
    at Object.<anonymous> (/mnt/Archive/Downloads/node_modules/serum-vial/dist/helpers.js:85:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/Archive/Downloads/node_modules/serum-vial/dist/boot_server.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /mnt/Archive/Downloads
npm ERR! command failed
npm ERR! command sh -c serum-vial

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/notooth/.npm/_logs/2021-12-26T04_12_48_590Z-debug.log
```

**Comment by thaaddeus** [comment]
You need to run with node.js version >=15.
