### ISSUE TITLE
Failed to run serum-vial

### ISSUE THREAD

**Issue by notooth1** [tardis-dev/serum-vial#41]
After running solana-test-validator and deploying serum-dex, I still cannot to run serum-vial. Can anyone help?
```
$ npx serum-vial --endpoint http://127.0.0.1:1024 --ws-endpoint-port 8899
...
2021-12-27T11:48:45.092Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":45.003}
2021-12-27T11:49:00.092Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":60.004}
2021-12-27T11:49:15.093Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":75.004}
2021-12-27T11:49:30.094Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":90.006}
2021-12-27T11:49:45.094Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":105.006}
2021-12-27T11:50:00.094Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":120.006}
2021-12-27T11:50:15.094Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":135.006}
2021-12-27T11:50:30.095Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":150.007}
2021-12-27T11:50:45.095Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":165.007}
2021-12-27T11:51:00.096Z info: No market data published for prolonged time {"lastPublishTimestamp":"2021-12-27T11:48:00.088Z","noDataPublishedForSeconds":180.007}
2021-12-27T11:51:13.691Z error: Serum producer worker 2 error occurred:  Error
    at RPCClient._getAccountInfoRPCResponseRaw (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/rpc_client.js:94:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async executeAndRetry (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/helpers.js:97:20)
    at async RPCClient.getAccountInfo (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/rpc_client.js:51:28)
    at async Function.load (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/@project-serum/serum/lib/market.js:133:45)
    at async SerumProducer.run (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/serum_producer.js:36:24) 
Uncaught Exception thrown Error
    at RPCClient._getAccountInfoRPCResponseRaw (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/rpc_client.js:94:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async executeAndRetry (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/helpers.js:97:20)
    at async RPCClient.getAccountInfo (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/rpc_client.js:51:28)
    at async Function.load (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/@project-serum/serum/lib/market.js:133:45)
    at async SerumProducer.run (/home/notooth/.npm/_npx/3cad36236d7e47f4/node_modules/serum-vial/dist/serum_producer.js:36:24)
uv loop at [0x7f81737fda98] has open handles:
[0x7f816010e420] poll (active)
        Close callback: 0xfcfa01fc8c400107 
        Data: 0x5b6f740 
        (First field): 0x7f816010e420 
uv loop at [0x7f81737fda98] has 1 open handles in total
node[3060801]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
 1: 0xb00d90 node::Abort() [node]
 2: 0xb00e0e  [node]
 3: 0xa73cd1  [node]
 4: 0xbc9e10 node::worker::Worker::Run() [node]
 5: 0xbc9e58  [node]
 6: 0x7f8182893ea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
 7: 0x7f81827c3def clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```

**Comment by thaaddeus** [comment]
looks like it can't get account info data from RPC node after multiple attempts, I guess you need to supply custom markets.json file with markets you deployed to your testnet dex?

**Comment by notooth1** [comment]
Is there any tutorial to do that?
