### ISSUE TITLE
mint not found Error: mint not found

### ISSUE THREAD

**Issue by Triggsy22** [tardis-dev/serum-vial#49]
Hello,

after the basic installation via 
`npx serum-vial`
or
```
npm install -g serum-vial
serum-vial
```
i get the _Error Serum producer worker 12 error occurred: mint not found Error: mint not found_

Here the full output:
```
2022-06-11T05:53:26.744Z info: Starting serum-vial server with options {"port":8000,"nodeEndpoint":"https://solana-api.projectserum.com","minionsCount":1,"commitment":"confirmed","bootDelay":500}
2022-06-11T05:53:26.746Z info: Starting single minion worker...
2022-06-11T05:53:27.286Z info: Listening on port 8000 {"minionId":1}
2022-06-11T05:53:27.390Z info: Starting serum producers for 140 markets, rpc endpoint: https://solana-api.projectserum.com
2022-06-11T05:53:27.870Z info: Serum producer starting for soALEPH/USDC market...
2022-06-11T05:53:28.336Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soALEPH/USDC","commitment":"confirmed"}
2022-06-11T05:53:28.435Z info: Serum producer starting for BTC/USDC market...
2022-06-11T05:53:28.755Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"BTC/USDC","commitment":"confirmed"}
2022-06-11T05:53:28.908Z info: Serum producer starting for soETH/USDC market...
2022-06-11T05:53:28.979Z info: Established new RPC WebSocket connection... {"market":"soALEPH/USDC"}
2022-06-11T05:53:28.979Z info: Serum producer started for soALEPH/USDC market...
2022-06-11T05:53:29.259Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soETH/USDC","commitment":"confirmed"}
2022-06-11T05:53:29.375Z info: Established new RPC WebSocket connection... {"market":"BTC/USDC"}
2022-06-11T05:53:29.375Z info: Serum producer started for BTC/USDC market...
2022-06-11T05:53:29.511Z info: Serum producer starting for SRM/USDC market...
2022-06-11T05:53:29.872Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"SRM/USDC","commitment":"confirmed"}
2022-06-11T05:53:29.896Z info: Established new RPC WebSocket connection... {"market":"soETH/USDC"}
2022-06-11T05:53:29.896Z info: Serum producer started for soETH/USDC market...
2022-06-11T05:53:29.987Z info: Serum producer starting for soSUSHI/USDC market...
2022-06-11T05:53:30.306Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soSUSHI/USDC","commitment":"confirmed"}
2022-06-11T05:53:30.514Z info: Established new RPC WebSocket connection... {"market":"SRM/USDC"}
2022-06-11T05:53:30.514Z info: Serum producer starting for soSXP/USDC market...
2022-06-11T05:53:30.514Z info: Serum producer started for SRM/USDC market...
2022-06-11T05:53:30.842Z info: Established new RPC WebSocket connection... {"market":"soSUSHI/USDC"}
2022-06-11T05:53:30.842Z info: Serum producer started for soSUSHI/USDC market...
2022-06-11T05:53:30.876Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soSXP/USDC","commitment":"confirmed"}
2022-06-11T05:53:31.037Z info: Serum producer starting for MSRM/USDC market...
2022-06-11T05:53:31.378Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"MSRM/USDC","commitment":"confirmed"}
2022-06-11T05:53:31.485Z info: Established new RPC WebSocket connection... {"market":"soSXP/USDC"}
2022-06-11T05:53:31.485Z info: Serum producer started for soSXP/USDC market...
2022-06-11T05:53:31.531Z info: Serum producer starting for soFTT/USDC market...
2022-06-11T05:53:31.907Z info: Established new RPC WebSocket connection... {"market":"MSRM/USDC"}
2022-06-11T05:53:31.907Z info: Serum producer started for MSRM/USDC market...
2022-06-11T05:53:31.974Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soFTT/USDC","commitment":"confirmed"}
2022-06-11T05:53:32.045Z info: Serum producer starting for soYFI/USDC market...
2022-06-11T05:53:32.617Z info: Serum producer starting for soLINK/USDC market...
2022-06-11T05:53:32.789Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soYFI/USDC","commitment":"confirmed"}
2022-06-11T05:53:33.171Z info: Serum producer starting for soHGET/USDC market...
2022-06-11T05:53:33.182Z info: Established new RPC WebSocket connection... {"market":"soFTT/USDC"}
2022-06-11T05:53:33.183Z info: Serum producer started for soFTT/USDC market...
2022-06-11T05:53:33.297Z info: Starting RPC client {"nodeWsEndpoint":"wss://solana-api.projectserum.com/","nodeRestEndpoint":"https://solana-api.projectserum.com","marketName":"soLINK/USDC","commitment":"confirmed"}
2022-06-11T05:53:33.678Z info: Serum producer starting for soCREAM/USDC market...
2022-06-11T05:53:33.921Z info: Established new RPC WebSocket connection... {"market":"soYFI/USDC"}
2022-06-11T05:53:33.922Z info: Serum producer started for soYFI/USDC market...
2022-06-11T05:53:33.972Z error: Serum producer worker 12 error occurred: mint not found Error: mint not found
    at throwIfNull (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:1078:15)
    at getMintDecimals (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:1048:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Function.load (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:143:55)
    at async SerumProducer.run (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\dist\serum_producer.js:36:24)
Uncaught Exception thrown Error: mint not found
    at throwIfNull (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:1078:15)
    at getMintDecimals (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:1048:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Function.load (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\node_modules\@project-serum\serum\lib\market.js:143:55)
    at async SerumProducer.run (C:\Users\user\AppData\Roaming\npm\node_modules\serum-vial\dist\serum_producer.js:36:24)
```

**Comment by Triggsy22** [comment]
if i use a custom config.json with way less entrys, its working.
So i think he problem is on my site.
Thanks for this great project :)
