### ISSUE TITLE
Issue with docker container

### ISSUE THREAD

**Issue by art1313** [tardis-dev/serum-vial#6]
docker logs serum_dex_socket 
```
2020-10-08T06:45:58.434Z serum-machine:serum-producer starting...
Unhandled Rejection at Promise Error: Out of order notification after publish: market: current slot 39982060, update slot: 39982060
    at AccountsNotification._update (/usr/local/lib/node_modules/serum-machine/dist/serum-producer.js:128:23)
    at Object.callback (/usr/local/lib/node_modules/serum-machine/dist/serum-producer.js:96:22)
    at Connection._wsOnAccountNotification (/usr/local/lib/node_modules/serum-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5209:17)
    at Client.emit (/usr/local/lib/node_modules/serum-machine/node_modules/eventemitter3/index.js:181:35)
    at /usr/local/lib/node_modules/serum-machine/node_modules/rpc-websockets/dist/lib/client.js:425:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5) Promise {
  <rejected> Error: Out of order notification after publish: market: current slot 39982060, update slot: 39982060
      at AccountsNotification._update (/usr/local/lib/node_modules/serum-machine/dist/serum-producer.js:128:23)
      at Object.callback (/usr/local/lib/node_modules/serum-machine/dist/serum-producer.js:96:22)
      at Connection._wsOnAccountNotification (/usr/local/lib/node_modules/serum-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5209:17)
      at Client.emit (/usr/local/lib/node_modules/serum-machine/node_modules/eventemitter3/index.js:181:35)
      at /usr/local/lib/node_modules/serum-machine/node_modules/rpc-websockets/dist/lib/client.js:425:22
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```

**Comment by thaaddeus** [comment]
it should be working now, just pull 'serum-vial' not 'serum-machine'
