### ISSUE TITLE
Unhandled Rejection at Promise Error: Out of order notification after publish

### ISSUE THREAD

**Issue by saleh-mir** [tardis-dev/serum-vial#8]
Hi there. Thank you for this package. 

I get this error after executing either the `npx` or the global `npm` setup:

```
Unhandled Rejection at Promise Error: Out of order notification after publish: market: current slot 41529994, update slot: 41529994
    at AccountsNotification._update (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/dist/serum-producer.js:128:23)
    at Object.callback (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/dist/serum-producer.js:96:22)
    at Connection._wsOnAccountNotification (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5209:17)
    at Client.emit (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/eventemitter3/index.js:181:35)
    at /Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/rpc-websockets/dist/lib/client.js:425:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5) Promise {
  <rejected> Error: Out of order notification after publish: market: current slot 41529994, update slot: 41529994
      at AccountsNotification._update (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/dist/serum-producer.js:128:23)
      at Object.callback (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/dist/serum-producer.js:96:22)
      at Connection._wsOnAccountNotification (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5209:17)
      at Client.emit (/Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/eventemitter3/index.js:181:35)
      at /Users/sully/.nvm/versions/node/v14.13.1/lib/node_modules/serum-machine/node_modules/rpc-websockets/dist/lib/client.js:425:22
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```

**Comment by thaaddeus** [comment]
Hi, this repo is very work in progress, and to make it work as I intendent it requires few updates in solana rpc so one can subscribe to multiple accounts notifications see https://github.com/tardis-dev/serum-machine/issues/7

**Comment by thaaddeus** [comment]
it should be working now, just install 'serum-vial' not 'serum-machine', 'level3' channel is functional, level2 is coming soon
